export const GET_REPOSITORY = 'GET_REPOSITORY'
export const GET_REPOSITORY_SUCCESSFUL = 'GET_REPOSITORY_SUCCESSFUL'
export const GET_REPOSITORY_FAILURE = 'GET_REPOSITORY_FAILURE'
export const REMOVE_REPOSITORY = 'REMOVE_REPOSITORY'